#!/usr/bin/env node
/**
 * Figma design tokens -> SCSS.
 *
 * Reads every `tokens/*.tokens.json` and writes:
 *   app/shared/styles/tokens/_css-vars.scss   :root / [data-theme] custom properties
 *   app/shared/styles/tokens/_variables.scss  $tokens map + flat $token-* Sass variables
 *
 * Supports both the W3C DTCG format ($value/$type, as exported by Figma Variables)
 * and the legacy Tokens Studio format (value/type).
 *
 * Usage: node scripts/build-tokens.mjs
 */

import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const tokensDir = path.join(root, 'tokens')
const stylesDir = path.join(root, 'app', 'shared', 'styles')
const outDir = path.join(stylesDir, 'tokens')

const FALLBACK_BREAKPOINTS = new Map([
  ['sm', '0'],
  ['md', '768px'],
  ['lg', '1280px'],
  ['xl', '1536px'],
  ['xxl', '1920px'],
])

/**
 * Read the `$breakpoints` map out of `_breakpoints.scss` so the Sass scale stays the
 * single source of truth: a mode named after a breakpoint becomes a `@media` block.
 */
async function readBreakpoints() {
  try {
    const source = await readFile(path.join(stylesDir, '_breakpoints.scss'), 'utf8')
    const block = source.match(/\$breakpoints:\s*\(([^)]*)\)/)
    if (!block) throw new Error('no $breakpoints map found')

    const entries = [...block[1].matchAll(/^\s*['"]?([\w-]+)['"]?\s*:\s*([^,\n]+?)\s*,?\s*$/gm)]
    if (entries.length === 0) throw new Error('$breakpoints map is empty')

    return new Map(entries.map(([, name, value]) => [name, value]))
  } catch (error) {
    console.warn(`  ! could not read $breakpoints (${error.message}); using defaults`)
    return FALLBACK_BREAKPOINTS
  }
}

/** Token types whose bare numeric values are pixel lengths. */
const LENGTH_TYPES = new Set([
  'dimension',
  'spacing',
  'sizing',
  'borderRadius',
  'borderWidth',
  'fontSize',
  'letterSpacing',
  'paragraphSpacing',
])

const BANNER =
  '// AUTO-GENERATED by scripts/build-tokens.mjs -- do not edit.\n' +
  '// Source: tokens/*.tokens.json. Regenerate with `bun run tokens`.\n'

const kebab = (segment) =>
  String(segment)
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[\s_.]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase()

const isToken = (node) =>
  node !== null &&
  typeof node === 'object' &&
  !Array.isArray(node) &&
  ('$value' in node || 'value' in node)

/** `{color.brand.primary}` -> `color-brand-primary` */
const aliasTarget = (raw) =>
  typeof raw === 'string' && /^\{[^{}]+\}$/.test(raw.trim())
    ? raw.trim().slice(1, -1).split('.').map(kebab).join('-')
    : null

function formatScalar(value, type) {
  if (typeof value === 'number') {
    return LENGTH_TYPES.has(type) && value !== 0 ? `${value}px` : String(value)
  }
  // DTCG dimension objects: { value: 16, unit: 'px' }
  if (value && typeof value === 'object' && 'unit' in value && 'value' in value) {
    return `${value.value}${value.unit}`
  }
  return String(value).trim()
}

function formatShadow(value) {
  const layers = Array.isArray(value) ? value : [value]
  return layers
    .map((layer) => {
      const parts = [
        layer.inset || layer.type === 'innerShadow' ? 'inset' : null,
        formatScalar(layer.offsetX ?? layer.x ?? 0, 'dimension'),
        formatScalar(layer.offsetY ?? layer.y ?? 0, 'dimension'),
        formatScalar(layer.blur ?? 0, 'dimension'),
        formatScalar(layer.spread ?? 0, 'dimension'),
        layer.color,
      ]
      return parts.filter(Boolean).join(' ')
    })
    .join(', ')
}

/**
 * Walk a token tree, pushing `{ name, value }` entries onto `out`.
 * `$type` declared on a group is inherited by its descendants (per the DTCG spec).
 */
function flatten(node, trail, out, inheritedType) {
  if (isToken(node)) {
    const name = trail.map(kebab).join('-')
    const type = node.$type ?? node.type ?? inheritedType
    const value = node.$value ?? node.value

    if (type === 'shadow' || type === 'boxShadow') {
      out.push({ name, value: formatShadow(value) })
      return
    }
    // Composite tokens (typography, border, ...) expand into one token per sub-property.
    if (value && typeof value === 'object' && !Array.isArray(value) && !('unit' in value)) {
      for (const [key, sub] of Object.entries(value)) {
        out.push({ name: `${name}-${kebab(key)}`, value: formatScalar(sub, key) })
      }
      return
    }
    out.push({ name, value: formatScalar(value, type) })
    return
  }

  if (node && typeof node === 'object' && !Array.isArray(node)) {
    const groupType = node.$type ?? node.type ?? inheritedType
    for (const [key, child] of Object.entries(node)) {
      if (key.startsWith('$')) continue // $description, $extensions, $themes, ...
      flatten(child, [...trail, key], out, groupType)
    }
  }
}

/** `theme.dark.tokens.json` -> 'dark'; `core.tokens.json` -> null (":root"). */
function modeOf(filename) {
  const stem = filename.replace(/\.tokens\.json$/i, '').replace(/\.json$/i, '')
  const parts = stem.split('.')
  return parts.length > 1 ? kebab(parts.at(-1)) : null
}

/**
 * Emit one mode's custom properties.
 *
 * - no mode / the base breakpoint -> plain `:root`
 * - a breakpoint name             -> `@media (min-width: ...) { :root { ... } }`
 * - anything else                 -> `[data-theme='<mode>']`
 */
function renderMode(mode, tokens, breakpoints) {
  const declarations = [...tokens].map(([name, value]) => `  --${name}: ${value};`).join('\n')
  const width = mode === null ? null : breakpoints.get(mode)

  if (width && width !== '0') {
    const indented = declarations.replace(/^/gm, '  ')
    return `\n@media (min-width: ${width}) {\n  :root {\n${indented}\n  }\n}\n`
  }

  // `null` (no mode) and the base breakpoint (`sm: 0`) both land on bare :root.
  const selector =
    mode === null || breakpoints.has(mode)
      ? ':root'
      : `:root[data-theme='${mode}'], [data-theme='${mode}']`

  return `\n${selector} {\n${declarations}\n}\n`
}

/** null first, then breakpoints in scale order, then themes alphabetically. */
function sortModes(modes, breakpoints) {
  const order = [...breakpoints.keys()]
  const rank = (mode) => {
    if (mode === null) return 0
    const index = order.indexOf(mode)
    return index >= 0 ? 1 + index : 1 + order.length
  }

  return [...modes].sort(
    (a, b) => rank(a) - rank(b) || String(a).localeCompare(String(b)),
  )
}

/**
 * Sass reads a bare top-level comma as an entry separator, so comma-separated values
 * (font stacks, multi-layer shadows) have to be parenthesised into a single list before
 * they can sit in a map or a variable declaration.
 */
function sassValue(value) {
  let depth = 0
  let quote = null

  for (const char of value) {
    if (quote) {
      if (char === quote) quote = null
      continue
    }
    if (char === '"' || char === "'") quote = char
    else if (char === '(' || char === '[') depth += 1
    else if (char === ')' || char === ']') depth -= 1
    else if (char === ',' && depth === 0) return `(${value})`
  }

  return value
}

/** Follow `{alias}` chains down to a literal, for the Sass-variable output. */
function resolveLiteral(name, literals, seen = new Set()) {
  const value = literals.get(name)
  if (value === undefined) return null
  const target = value.startsWith('var(--') ? value.slice(6, value.indexOf(')')) : null
  if (!target) return value
  if (seen.has(name)) {
    console.warn(`  ! circular alias at "${name}"`)
    return value
  }
  seen.add(name)
  return resolveLiteral(target, literals, seen) ?? value
}

async function main() {
  if (!existsSync(tokensDir)) await mkdir(tokensDir, { recursive: true })
  await mkdir(outDir, { recursive: true })

  const files = (await readdir(tokensDir)).filter((f) => f.toLowerCase().endsWith('.json')).sort()

  /** @type {Map<string|null, Map<string, string>>} mode -> name -> css value */
  const byMode = new Map()

  for (const file of files) {
    const raw = await readFile(path.join(tokensDir, file), 'utf8')
    let json
    try {
      json = JSON.parse(raw)
    } catch (error) {
      console.error(`  x ${file}: invalid JSON -- ${error.message}`)
      process.exitCode = 1
      continue
    }

    const mode = modeOf(file)
    const entries = []
    flatten(json, [], entries)

    const bucket = byMode.get(mode) ?? new Map()
    for (const { name, value } of entries) {
      const alias = aliasTarget(value)
      bucket.set(name, alias ? `var(--${alias})` : value)
    }
    byMode.set(mode, bucket)
    console.log(`  + ${file} -> ${entries.length} tokens${mode ? ` [${mode}]` : ''}`)
  }

  const breakpoints = await readBreakpoints()
  const modes = sortModes(byMode.keys(), breakpoints)

  // --- _css-vars.scss ---------------------------------------------------------
  let css = BANNER
  if (modes.length === 0) {
    css += '\n// No token files found in tokens/. Drop a Figma export there and rerun.\n'
  }
  for (const mode of modes) {
    css += renderMode(mode, byMode.get(mode), breakpoints)
  }
  await writeFile(path.join(outDir, '_css-vars.scss'), css, 'utf8')

  // --- _variables.scss --------------------------------------------------------
  // Literal (alias-resolved) values, for Sass-time math, colour functions and maps.
  // Only the base scale: per-breakpoint and per-theme overrides exist at runtime only.
  const baseMode = [...breakpoints].find(([, width]) => width === '0')?.[0]
  const literals = new Map([...(byMode.get(null) ?? []), ...(byMode.get(baseMode) ?? [])])
  const resolved = [...literals.keys()].map((name) => [
    name,
    resolveLiteral(name, literals) ?? literals.get(name),
  ])

  let scss = BANNER
  if (resolved.length === 0) {
    scss += '\n// No token files found in tokens/. Drop a Figma export there and rerun.\n\n$tokens: ();\n'
  } else {
    scss +=
      '\n// Literal token values, for Sass-time use (maths, colour functions, media queries).\n' +
      '// In components use the custom property directly -- `padding: var(--spacing-200)` --\n' +
      '// so per-breakpoint and per-theme overrides still apply at runtime.\n'
    scss += '\n$tokens: (\n'
    for (const [name, value] of resolved) scss += `  '${name}': ${sassValue(value)},\n`
    scss += ');\n\n'
    for (const [name, value] of resolved) scss += `$token-${name}: ${sassValue(value)};\n`
  }
  await writeFile(path.join(outDir, '_variables.scss'), scss, 'utf8')

  const total = [...byMode.values()].reduce((sum, bucket) => sum + bucket.size, 0)
  console.log(`\n  ${total} tokens across ${modes.length} mode(s) -> app/shared/styles/tokens/`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
